[build]
  functions = "netlify/functions"
  command = "npm ci --omit=dev || npm i"

# Redirect POSTs to the serverless function
[[redirects]]
  from = "/county_data"
  to = "/.netlify/functions/county_data"
  status = 200

[functions]
  # Bundle the SQLite database and the sql.js wasm asset into the function
  included_files = [
    "data.db",
    "node_modules/sql.js/dist/sql-wasm.wasm"
  ]
